---
title: "Untitled"
author: "Christian Pascual"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
a = readRDS("data.rds")
data = a$data
covars = a$covar_params
outcomes = a$outcome_params
coefmat = a$coefmat
formula.list = a$formulas
init = 'mle'
mu0 = NULL
```

note to self: the reordering of the outcomes is due to how the Stan file is coded up

```{r}
# Gut the gcglm function
library(cmdstanr)

# Prof Alt's Stan file for the GCGLM
mod = cmdstan_model('glm_copula_cmdstanr.stan')

N  = nrow(data)
J  = length(formula.list)

# Reorder variables if necessary
family.list = lapply(1:J, function(j) outcomes[[j]][["family"]])
n.indx = which(family.list == 'Normal')
b.indx = which(family.list == 'Bernoulli')
p.indx = which(family.list == 'Poisson')
new.order = c(n.indx, b.indx, p.indx)

## Count the number of outcomes of each type
Jn = length(n.indx)
Jb = length(b.indx)
Jp = length(p.indx)

# Isolate the data columns for each outcome type and make Stan friendly
Y = data %>% select(contains("Y")) 
Yn = Y %>% select(contains("Y")) %>% select(n.indx) %>% as.matrix
Yb = Y %>% select(contains("Y")) %>% select(b.indx) %>% as.matrix
Yp = Y %>% select(contains("Y")) %>% select(p.indx) %>% as.matrix

# Organize design matrices and number of covariates per regression
Xlist = lapply(formula.list, model.matrix, data = data)
Xbig  = do.call(cbind, Xlist)

# Count the total number of covariates from design matrices + for each outcome
K = ncol(Xbig)
Kj = sapply(Xlist, ncol)

# Define endpoints to delineate correct design matrix to use in Stan
Xindx  = matrix(nrow = J, ncol = 2)
xstart = 1
for ( j in 1:J ) {
  xend = xstart + Kj[j] - 1
  Xindx[j, ] = c(xstart, xend)
  xstart = xend + 1
}

args = list()
chains = args$chains
if (is.null(chains) ) chains = 4

if ( !all( new.order == 1:J ) ) {
  outcomes = outcomes[new.order]
  formula.list = formula.list[new.order]
  family.list  = family.list[new.order]
  family.list = lapply(family.list, function(x) { tolower(x) })
  
  family.list[[1]] = "gaussian" # adding just to hotfix this code
  family.list[[2]] = "binomial" # adding just to hotfix this code
}

fitlist = mapply(function(f, fam) glm(formula = f, family = fam, data = data), f = formula.list, fam = family.list, SIMPLIFY = F)
beta.start    = sapply(fitlist, coef)
sigmasq.start = sapply( fitlist[sapply(family.list, function(fam) fam == 'gaussian')], function(x) summary(x)$dispersion )
sigmasq.start = as.array(sigmasq.start)

# Approximate MLE of correlation matrix
betalist = lapply(fitlist, function(f) coef(f))
Un = matrix(nrow = N, ncol = Jn)
Ub = matrix(nrow = N, ncol = Jb)
Up = matrix(nrow = N, ncol = Jp)
j = 1
jn = 1
jb = 1
jp = 1

while ( jn <= Jn ) {
      Un[, jn] = pnorm(Yn[, j],
                       mean = outcomes[[j]]$linkinv(Xlist[[j]] %*% betalist[[j]]),
                       sd = sqrt(summary(fitlist[[j]])$dispersion) )
      jn = jn + 1
      j  = j  + 1
}

while ( jb <= Jb ) {
      mu = outcomes[[j]]$linkinv(Xlist[[j]] %*% betalist[[j]])
      Ub[, jb] = rowMeans(
        cbind(
          min = pbinom(Yb[, jb] - 1, size = 1, prob = mu),
          max = pbinom(Yb[, jb], size = 1, prob = mu)
        )
      )
      jb = jb + 1
      j  = j  + 1
}

while ( jp <= Jp ) {
      mu = outcomes[[j]]$linkinv(Xlist[[j]] %*% betalist[[j]])
      Up[, jp] = rowMeans(
        cbind(
          min = ppois(Yp[, jp] - 1, lambda = mu),
          max = ppois(Yp[, jp], lambda = mu)
        )
      )
      jp = jp + 1
      j  = j  + 1
}

Gamma.start = cor(cbind(Un, Ub, Up))
L = t(chol(Gamma.start))

# Set initial values to the MLE; each MCMC chain needs a copy
init = lapply(1:chains, function(i)
      list(
        'beta' = unlist(beta.start),
        'sigmasq' = sigmasq.start,
        'L' = L,
        'uraw_b' = Ub,
        'uraw_p' = Up
      )
    )

mu0 = NULL
if ( is.null(mu0) ) {
    mu0 = matrix(0, nrow = N, ncol = J)
    for ( j in 1:J ) {
      if(family.list[[j]] == 'binomial')
        mu0[, j] = 0.5
      if(family.list[[j]] == 'poisson')
        mu0[, j] = 1
    }
}

lambda = NULL
## Set default value of lambda
  if ( is.null(lambda) )
    lambda = rep(0.01, J)
  if ( length(lambda) == 1 )
    lambda = rep(lambda, J)
  if ( length(lambda) != J )
    stop("lambda0 must be a scalar or vector of dimension length(formula.list)")

standat = list(
    'N'      = N,         # number of observations
    'J'      = J,         # total number of outcomes
    'Jn'     = Jn,        # number of normal outcomes
    'Jb'     = Jb,        # number of binomial outcomes
    'Jp'     = Jp,        # number of poisson outcomes
    'K'      = K,         # number of covariates for concatenated design matrices (X1, .., XK)
    'Yn'     = Yn,        # normal outcomes
    'Yb'     = Yb,        # bernoulli outcomes
    'Yp'     = Yp,        # poisson outcomes
    'X'      = Xbig,      # concatenated design matrices (X1, ..., XK)
    'Xindx'  = Xindx,     # Jx2 integer array giving the start and end indexes of X matrix for each outcome
    'Kj'     = Kj,        # J-dim integer array giving how many covariates per outcome
    'mu0'    = mu0,       # matrix giving prior prediction for each response (for Chen-Ibrahim (2003) conjugate prior of GLM)
    'lambda' = lambda     # precision parameters for conjugate prior of Chen and Ibrhaim (2003)
  )

fit = mod$sample(data = standat, init = init)

draws = as_draws_df(fit$draws()) %>% 
  select(contains("beta"), contains("sigmasq"), contains("Gamma"))

# Rename betas to align with indexing by outcome + predictor
# Ex: beta[j][i]: is the i-th coef of j-th outcome/model
adj.beta.names = c()
start = 1
for (j in 1:J) {
  numCoefs = length(betalist[[j]])
  adj.beta.names = c(adj.beta.names, 
                     paste0("beta[", j, "][", 1:numCoefs  ,"]"))
  # Adjust starting point
  start = start + numCoefs
}
colnames(draws)[1:length(adj.beta.names)] = adj.beta.names

list(
    'samples'      = draws,
    'formula.list' = formula.list,
    'family.list'  = family.list,
    'n.gaussian'   = Jn,
    'n.bernoulli'  = Jb,
    'n.poisson'    = Jp
  )
```





Pulling out some code that I don't understand

```{r}
Yb
cbind(min = pbinom(Yb[, 1] - 1, size = 1, prob = mu),
      max = pbinom(Yb[, 1], size = 1, prob = mu))
```

